name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download and install minikube to /usr/local/bin
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
            && sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Verify system has virtualization support enabled
        run: |
          egrep -q 'vmx|svm' /proc/cpuinfo && echo yes || echo no

        # If you are running within a VM, your hypervisor does not allow nested virtualization.
        # You will need to use the None (bare-metal) driver.
      - name: Start Minikube and create a cluster
        run: |
          sudo minikube start --vm-driver=none