name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download and install minikube to /usr/local/bin
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
            && sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Verify system has virtualization support enabled
        run: egrep -q 'vmx|svm' /proc/cpuinfo && echo yes || echo no 

        # If you are running within a VM, your hypervisor does not allow nested virtualization.
        # You will need to use the None (bare-metal) driver.
        # https://minikube.sigs.k8s.io/docs/start/linux/
      - name: Start minikube and create a cluster
        env:
          # To use kubectl or minikube commands as your own user, you may need to relocate them.
          # This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
          CHANGE_MINIKUBE_NONE_USER: true
        run: |
          # https://github.com/kubernetes/minikube/issues/3323#issuecomment-472916946
          sudo -E minikube start --vm-driver=none --kubernetes-version v1.16.2 --extra-config kubeadm.ignore-preflight-errors=SystemVerification
      
      - name: List all pods in the cluster
        run: kubectl get pods -A

      - name: Enable the NGINX ingress controller
        run: minikube addons enable ingress
