name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download and install minikube to /usr/local/bin
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
            && sudo install minikube-linux-amd64 /usr/local/bin/minikube
